Add Hebrew translation
sddm/sddm pull request #1298
Opened 2020-10-03 16:50 UTC by omeritzics

2020-10-05 10:37 UTC, plfiorini requested changes
Please add he.ts to https://github.com/sddm/sddm/blob/develop/data/translations/CMakeLists.txt

2020-10-05 14:04 UTC, omeritzics commented
> Please add he.ts to https://github.com/sddm/sddm/blob/develop/data/translations/CMakeLists.txt

OK, I did it.

2020-10-12 09:46 UTC, omeritzics commented
@plfiorini I made the requested changes.

2020-10-12 10:07 UTC, plfiorini approved these changes

2020-10-12 10:08 UTC, merged