Error in elarun theme
sddm/sddm pull request #1336
Opened 2020-11-29 09:05 UTC by mvlvrd

Fixes #1272

When running sddm with elarun in Debian I get the following (seemingly innocuous) error message:

file:///usr/share/sddm/themes/debian-theme/Main.qml:155: ReferenceError: session_button is not defined

The button in question was removed in #521

I have removed the references in my local branch:
mvlvrd@1283919
and run it without issue.

2020-11-29 18:21 UTC, Pointedstick approved these changes
LGTM

2020-11-29 18:26 UTC, davidedmundson requested changes
session_button may be removed, but this surely leaves tab/backtab on those two buttons broken.

Shouldn't it point to the next button in the chain instead of removing it?

2020-12-13 10:50 UTC, mvlvrd commented
Thanks for the review. The two broken buttons now have both tab/backtab references.

2021-03-13 16:39 UTC, plfiorini approved these changes

2021-03-14 07:07 UTC, merged