add bulgarian tranlsation
sddm/sddm pull request #1343
Opened 2020-12-10 11:50 UTC by mkkDr2010

Here the .ts file
[bg.zip](https://github.com/sddm/sddm/files/5672466/bg.zip)

2021-01-10 22:54 UTC, mathieujobin commented on src/daemon/XorgDisplayServer.cpp
> +            qCritical("Failed to open pipe to start X Server");
why so much changes for adding bulgarian translation?

2021-02-21 22:05 UTC, plfiorini commented
There are many unrelated commits

2021-02-21 22:05 UTC, plfiorini requested changes
Many unrelated commits, please clean the PR

2021-02-22 03:38 UTC, mathieujobin commented
this is a common pattern when you mix git merges with rebase.

I am guessing he had many branches that are not his included in his branch, which got rebased unto master. but he did a git pull and merged the rebase commits.

the solution here is to rebase everything one more time with `master`.

but OH ! did `develop` and `master` went out of sync?

2021-02-22 03:40 UTC, mathieujobin commented
looks like he opened a PR with develop onto master, probably a mistake. 
his translation isn't even part of this PR 

lets close this BEFORE you update master with develop, otherwise, github will automatically show it as merged.

2021-02-22 03:40 UTC, mathieujobin requested changes
please close and open fresh one

2021-02-22 12:06 UTC, closed without merging