Iterate PR using Wayland for the greeter
sddm/sddm pull request #1367
Opened 2021-02-15 22:49 UTC by aleixpol

This is mostly based on the work @plfiorini did in https://github.com/sddm/sddm/pull/616.

Biggest changes are:
* Decoupling the compositor implementation from SDDM by making it configurable.
* Executing both the compositor and the client on from same pam-authenticated process, otherwise our compositor gets killed when the greeter is launched.

2021-02-16 10:53 UTC, plfiorini commented
Thanks for resurrecting this, I will give it a spin

2021-02-16 12:57 UTC, davidedmundson commented on src/auth/Auth.h
> +        void setDisplayServer(bool on = true);
Is this still used?

2021-02-16 13:00 UTC, davidedmundson requested changes
Bugs we need to fix before landing:
 - From what I can tell, starting an X11 session isn't going to work? 
 
 - We might want some fallback to X if the wayland greeter fails?
 
Bugs that I am happy to say we address in the future

 - Default keyboard layout won't be loaded from localectl on Plasma
 (arguably this is due to a very weird design decision in locale1 not being in kwin but in startplasma)
 
 - Multi-seat will be broken. That will have two users on wayland-0

2021-02-16 13:09 UTC, plfiorini commented
@davidedmundson Multi-seat: the compositor should create a socket whose name references the seat, like `sddm-wayland-$SEAT`

2021-02-16 13:12 UTC, zzag commented
@plfiorini I believe the issue is that there is no generic way to say "compositor $foo, please bind the following socket $xyz"

2021-02-16 13:16 UTC, plfiorini requested changes

2021-02-16 13:16 UTC, plfiorini commented on src/helper/HelperStartWayland.cpp
> +    auto watcher = new SDDM::WaylandSocketWatcher(&app, QProcessEnvironment::systemEnvironment());
Set `WAYLAND_SOCKET` to `sddm-wayland-$SEAT` here or where the helper is called.
Here is probably better as you can set it only when the compositor process is spawned.

2021-02-16 13:17 UTC, plfiorini commented
> @plfiorini I believe the issue is that there is no generic way to say "compositor $foo, please bind the following socket $xyz"

Set `WAYLAND_DISPLAY` on the user session.

2021-02-16 13:23 UTC, zzag commented
This is going to work only if the compositor calls `wl_display_add_socket()` with a `nullptr` socket name. However, many compositors nowadays use `wl_display_add_socket_auto()`, which doesn't check WAYLAND_DISPLAY.

2021-02-16 13:31 UTC, plfiorini commented
> This is going to work only if the compositor calls `wl_display_add_socket()` with a `nullptr` socket name. However, many compositors nowadays use `wl_display_add_socket_auto()`, which doesn't check WAYLAND_DISPLAY.

But `wl_display_add_socket_auto()` scans through `$XDG_RUNTIME_DIR`  for an unused wayland-$d (where $d is < 32) and binds the first available.

2021-02-16 13:46 UTC, plfiorini commented
Having the compositor configurable will give us more flexibility, but the default runs `weston` with its shell.
We should be using fullscreen-shell since I wrote a shell integration for Qt upstream a long time ago.

2021-02-16 13:47 UTC, plfiorini requested changes

2021-02-16 13:47 UTC, plfiorini commented on src/common/Configuration.h
> +            Entry(CompositorCommand,   QString,     _S("weston"),                               _S("Choose which Wayland compositor we will be starting"));
`weston --shell=fullscreen-shell.so`

2021-02-16 13:47 UTC, plfiorini commented on src/common/Configuration.h
> +            Entry(CompositorCommand,   QString,     _S("weston"),                               _S("Choose which Wayland compositor we will be starting"));
and then run the greeter setting `QT_WAYLAND_SHELL_INTEGRATION=fullscreen-shell-v1`

2021-02-16 13:49 UTC, plfiorini commented
There is no keyboard layout switching.
As far as I know there is no API to list the keymaps, we should be doing it ourselves.
We should also make a protocol between the greeter and the compositor for switching it.

2021-02-16 13:53 UTC, plfiorini commented
@aleixpol Why not doing a small compositor for SDDM, it's so easy with QtWayland?

That would give us maximum control over it.
We could keep the setting so that users can use their own compositor, after all we do the same thing for the X display server.

2021-02-16 16:35 UTC, aleixpol commented
> @aleixpol Why not doing a small compositor for SDDM, it's so easy with QtWayland?

It's always a possibility. My impression is that whatever we do will meet escalating requirements. I know that for example by using kwin we could easily integrate the KScreen configuration between both easily. Also things like keyboard switching we can implement just once. With a KDE mindset we want to avoid the risk of maintaining two stacks.

2021-02-17 01:42 UTC, aleixpol commented
With my last commit I made it so Xorg starts. Only one problem: it doesn't work.

This is the tail of my Xorg.0.log, maybe someone here knows something about starting X sessions ^^'.

```
[   103.794] (II) modeset(0): Output DP-1 using initial mode 3840x2160 +0+0
[   103.794] (II) modeset(0): Output HDMI-1 using initial mode 1920x1200 +3840+0
[   103.794] (==) modeset(0): Using gamma correction (1.0, 1.0, 1.0)
[   103.794] (==) modeset(0): DPI set to (96, 96)
[   103.794] (II) Loading sub module "fb"
[   103.794] (II) LoadModule: "fb"
[   103.794] (II) Loading /usr/lib/xorg/modules/libfb.so
[   103.794] (II) Module fb: vendor="X.Org Foundation"
[   103.794]    compiled for 1.20.10, module version = 1.0.0
[   103.794]    ABI class: X.Org ANSI C Emulation, version 0.4
[   103.794] (EE) modeset(0): drmSetMaster failed: Device or resource busy
[   103.794] (EE) 
Fatal server error:
[   103.794] (EE) AddScreen/ScreenInit failed for driver 0
[   103.794] (EE) 
```

2021-02-17 06:56 UTC, plfiorini commented
We should be using rootless Xorg (Xorg with user privileges): https://wiki.archlinux.org/index.php/xorg#Rootless_Xorg

2021-02-18 14:52 UTC, aleixpol commented
> We should be using rootless Xorg (Xorg with user privileges)

I gave it a go, not really working (yet?). I hope we could do both approaches separately so this doesn't become a big fat PR supposed to solve every problem.

https://github.com/aleixpol/sddm/pull/1

2021-02-18 15:36 UTC, plfiorini commented
> > We should be using rootless Xorg (Xorg with user privileges)
> 
> I gave it a go, not really working (yet?). I hope we could do both approaches separately so this doesn't become a big fat PR supposed to solve every problem.
> 
> [aleixpol#1](https://github.com/aleixpol/sddm/pull/1)

I don't remember what was missing from my patch.

What is missing?

2021-02-18 16:37 UTC, aleixpol commented
> > > We should be using rootless Xorg (Xorg with user privileges)
> > 
> > 
> > I gave it a go, not really working (yet?). I hope we could do both approaches separately so this doesn't become a big fat PR supposed to solve every problem.
> > [aleixpol#1](https://github.com/aleixpol/sddm/pull/1)
> 
> I don't remember what was missing from my patch.
> 
> What is missing?

I cannot get it to work. Also it seems to be launching separate Auth for the session and the X server which this PR already addresses for Wayland because it doesn't work.

2021-02-21 22:03 UTC, plfiorini commented
> > > > We should be using rootless Xorg (Xorg with user privileges)
> > > 
> > > 
> > > I gave it a go, not really working (yet?). I hope we could do both approaches separately so this doesn't become a big fat PR supposed to solve every problem.
> > > [aleixpol#1](https://github.com/aleixpol/sddm/pull/1)
> > 
> > 
> > I don't remember what was missing from my patch.
> > What is missing?
> 
> I cannot get it to work. Also it seems to be launching separate Auth for the session and the X server which this PR already addresses for Wayland because it doesn't work.

I'm updating the original Xorg rootless PR so we can reuse some bits here.

2021-02-22 07:36 UTC, plfiorini requested changes

2021-02-22 07:36 UTC, plfiorini commented on src/helper/HelperStartWayland.cpp
> +        return true;
I guess it was meant to be `return false`

2021-02-22 07:36 UTC, plfiorini commented on src/helper/HelperStartWayland.cpp
> +    if (!p->waitForStarted()) {
10s timeout?

2021-02-22 07:36 UTC, plfiorini commented on src/helper/HelperStartWayland.cpp
> +        if (!p->waitForFinished()) {
5s timeout?

2021-03-07 19:39 UTC, tpgxyz commented
Hi, I am happy to report that sddm works with Wayland greeter. I'm running it for a whole day.

For an experiment I build sddm rpm for OpenMandriva with this PR and adjusted sddm.conf to use Wayland as display.

One thing I noticed I that after leaving greeter to plasma Wayland is see for 1 sec my TTY line prompt.

2021-03-13 16:36 UTC, plfiorini commented
Now that there's #1379 this is obsolete.
Only thing missing from #1379 compared to this one, is the compositor environment setting that can be added later.

2021-06-08 06:48 UTC, closed without merging