Upstream freebsd patches
sddm/sddm pull request #1369
Opened 2021-02-19 23:19 UTC by adriaandegroot

These are downstream (packaging) patches that we carry against the 0.19 release. I can't tell whether they should go to *devel* or *master*, so I picked one. These patches were created by @arrowd , I'm just pushing them here (come to think of it, I should have set `--author`).

The **reason** I'm throwing them out here is that @aleixpol was shaming me for having downstream patches, and @davidedmundson asked me to take a look at @Vogtinator 's rework-xauth #1230 for FreeBSD -- except that doesn't apply on top of our patches, so I need to untangle bits **anyway**.

2021-02-19 23:51 UTC, adriaandegroot commented
The latter three commits are @Vogtinator 's Xauth, followed by build fixes; those could be incorporated in the upstream commit, although I had to massage it a little to fit with the other changes from FreeBSD (e2e2684 clashes with it).

2021-02-20 00:28 UTC, aleixpol reviewed
LGTM otherwise. I guess it would make sense to merge Vogt's patch first though.

2021-02-20 00:28 UTC, aleixpol commented on src/helper/UserSession.cpp
>              QProcess::start(cmd);
Should be ported to:
`QProcess::start(mainConfig.X11.SessionCommand.get(), {m_path});`

The current QProcess::start(cmd) that we're using everywhere is deprecated anyway. I'm not sure if SessionCommand can have arguments, if so we'll need to use QProcess::splitCommand().

2021-02-20 11:39 UTC, arrowd approved these changes
> These patches were created by @arrowd , I'm just pushing them here 

Not really, exactly these patches were already in place when I started fiddling with SDDM. My own patches were submitted in https://github.com/sddm/sddm/pull/1234 , so no need in changing commits author.

The PR looks OK, except "Redesign xauth handling", for which I can't provide a review.

Thanks for upstreaming this!

2021-02-20 11:39 UTC, arrowd commented on CMakeLists.txt
> +find_library(_xau_lib
According to [docs](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html), `LIBXAU_LINK_LIBRARIES` should contain libraries with absolute paths. Doesn't that work?

2021-03-14 07:31 UTC, plfiorini commented
We use git flow, so PRs have to target `develop`.
Also, why you did include @Vogtinator's patch for Xauth here, can you make a couple of separate PR's?

2021-03-14 07:31 UTC, plfiorini requested changes
See comments

2021-06-09 20:34 UTC, Pointedstick commented
Ping @adriaandegroot

2021-06-10 16:07 UTC, adriaandegroot commented
There's no point in leaving this open in parallel with #1230

2021-06-10 16:07 UTC, closed without merging