Mark wayland support as experimental
sddm/sddm pull request #1737
Opened 2023-06-22 18:02 UTC by davidedmundson

2023-06-22 18:35 UTC, Vogtinator requested changes, later dismissed

2023-06-22 18:35 UTC, Vogtinator commented on README.md
> +SDDM is a modern display manager for X11 (with experimental Wayland support) aiming to
This sounds like it's also experimental to start Wayland sessions, which is not the case

2023-06-22 18:35 UTC, Vogtinator commented on src/common/Configuration.h
> +            Entry(CompositorCommand,   QString,     _S("weston --shell=fullscreen-shell.so"),   _S("Path of the Wayland compositor to execute when starting the greeter (Experimental)"));
This option isn't really experimental, only `DisplayServer=wayland` is

2023-06-23 12:26 UTC, hsitter approved these changes
lgtm

2023-06-23 12:28 UTC, merged

2023-06-23 12:32 UTC, Vogtinator reviewed
Retroactive +1

2023-06-23 12:32 UTC, Vogtinator commented
(Interesting how GitHub still shows that a review is pending but I can't approve it - only comment)