Respond to SecureAttentionKey events from logind (once the MR for logind is merged
sddm/sddm pull request #1922
Opened 2024-04-30 03:07 UTC by n3rdopolis

This depends on https://github.com/systemd/systemd/pull/29542 not merged yet, subject to change

The first commit fixes an issue where the greeter hangs if SwitchToGreeter double fires.
Something that if the systemd MR is merged will be easier for users to accidentally trigger, at least with logind, as it is possible to hit Ctrl+Alt+Shift+Esc or whatever the final sequence is, when the greeter is active

dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.DisplayManager $XDG_SEAT_PATH org.freedesktop.DisplayManager.Seat.SwitchToGreeter
sleep 5
dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.DisplayManager $XDG_SEAT_PATH org.freedesktop.DisplayManager.Seat.SwitchToGreeter

2024-04-30 10:00 UTC, Vogtinator requested changes

2024-04-30 10:00 UTC, Vogtinator commented on src/daemon/SeatManager.cpp
> +        auto logindSeat = m_systemSeats.take(name);
`take` removes it from the list, is that intentional? I don't think the key implies that the seat got removed.

2024-04-30 10:00 UTC, Vogtinator commented on src/daemon/Seat.cpp
> +        if (Logind::isAvailable()) {
Should IMO be done internally in `SeatManager::switchToGreeter`, iterate all displays and check whether it's a greeter.

2024-04-30 10:01 UTC, Vogtinator commented
> The first commit fixes an issue where the greeter hangs if SwitchToGreeter double fires.

Why does it hang? Technically it should work to have multiple greeters on the same seat simultaneously, even though it does not make sense.

2024-04-30 10:50 UTC, n3rdopolis commented on src/daemon/SeatManager.cpp
> +        auto logindSeat = m_systemSeats.take(name);
Woah, that is not intentional. Will fix

Thanks

2024-04-30 11:11 UTC, n3rdopolis commented
> > The first commit fixes an issue where the greeter hangs if SwitchToGreeter double fires.
> 
> Why does it hang? Technically it should work to have multiple greeters on the same seat simultaneously, even though it does not make sense.

If it helps, it's when I am using xorg-user as the greeter. I have not tested on my multiseat vm yet so it's only seat0 that I saw this

I am not sure why it hangs, it only hangs if you try to activate the greeter _again_ when the greeter is active. 
If the greeter is _running_, but not the active session it's OK

It seems to be something to do with the xserver itself or something? Because it's seems to be the display server that acts up, it doesn't respond to Ctrl+Alt+Fx either...

2024-04-30 13:00 UTC, Vogtinator commented
> > > The first commit fixes an issue where the greeter hangs if SwitchToGreeter double fires.
> > 
> > 
> > Why does it hang? Technically it should work to have multiple greeters on the same seat simultaneously, even though it does not make sense.
> 
> If it helps, it's when I am using xorg-user as the greeter. I have not tested on my multiseat vm yet so it's only seat0 that I saw this
> 
> I am not sure why it hangs, it only hangs if you try to activate the greeter _again_ when the greeter is active. If the greeter is _running_, but not the active session it's OK
> 
> It seems to be something to do with the xserver itself or something? Because it's seems to be the display server that acts up, it doesn't respond to Ctrl+Alt+Fx either...

Maybe a deadlock during VT switch?

2024-04-30 14:32 UTC, n3rdopolis commented
> > > > The first commit fixes an issue where the greeter hangs if SwitchToGreeter double fires.
> > > 
> > > 
> > > Why does it hang? Technically it should work to have multiple greeters on the same seat simultaneously, even though it does not make sense.
> > 
> > 
> > If it helps, it's when I am using xorg-user as the greeter. I have not tested on my multiseat vm yet so it's only seat0 that I saw this
> > I am not sure why it hangs, it only hangs if you try to activate the greeter _again_ when the greeter is active. If the greeter is _running_, but not the active session it's OK
> > It seems to be something to do with the xserver itself or something? Because it's seems to be the display server that acts up, it doesn't respond to Ctrl+Alt+Fx either...
> 
> Maybe a deadlock during VT switch?

Could be, or it could be it trying to restart the greeter/server incompletely or something

If I try to vt switch away from the greeter vt and back to it, it still seems to deadlock (This is with QEMU's virtual serial console that I am able to run the chvt commands)

It could also be an older xserver.... or just this VM

Are you able to replicate with x11-user and these sets of commands

```
dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.DisplayManager $XDG_SEAT_PATH org.freedesktop.DisplayManager.Seat.SwitchToGreeter
sleep 5
dbus-send --system --type=method_call --print-reply --dest=org.freedesktop.DisplayManager $XDG_SEAT_PATH org.freedesktop.DisplayManager.Seat.SwitchToGreeter
```
by chance?

2024-05-03 03:08 UTC, n3rdopolis commented
Testing on a clean Kubuntu 24.04 ISO, with that set of commands to double-fire SwitchToGreeter, and well it seems that instead of hanging, it is starting the greeter twice, first on tty1, then on tty3,

It defaults to running Xorg as root, and not x11-user, it seems like that this is the issue, it is trying another instance, it just was starting multiple greeters before, and maybe x11-user is different, and is stepping on the first instance, maybe that explains the hang

2024-06-24 21:23 UTC, n3rdopolis commented
https://github.com/systemd/systemd/pull/29542 is now merged

2024-06-25 17:27 UTC, Vogtinator commented on src/daemon/SeatManager.cpp
> +        if (Logind::isAvailable()) {
Add a comment, like

```
// Switch to existing greeter session if available
```

2024-06-25 17:28 UTC, Vogtinator commented
I wonder whether this should be handled by `Seat.cpp` instead, it could iterate all of `m_display` and check whether it is an available greeter. Might need some refactoring though...

2024-06-25 17:30 UTC, Vogtinator commented
In the case of using x11user or wayland as display server, the greeter is handled separately from the session and is only stopped 5s after successful login. I imagine that in some cases (e.g. apparent hang) the SAK may get pressed in between and it might switch to an effectively zombie greeter.

2024-06-26 16:36 UTC, n3rdopolis commented
What would need to be moved? I did a lot of this by grepping though, so I am not 100% familiar...

2024-06-26 16:45 UTC, Vogtinator commented
> What would need to be moved? I did a lot of this by grepping though, so I am not 100% familiar...

Not sure. The main issue I see that might happen in practice is https://github.com/sddm/sddm/blob/ae072f901671b68861da9577e3e12e350a9053d5/src/daemon/Display.cpp#L557

Would be great if you could confirm that this is the case.

Doing the switch internally instead of through logind makes it independent of logind and also more reliable IMO.

2024-06-26 17:01 UTC, n3rdopolis commented
Just to make sure I understand,, this is that that 5 second timer that quits the greeter might cause the greeter to quit, but the display server to still be running, correct?

2024-06-26 17:15 UTC, Vogtinator commented
> Just to make sure I understand,, this is that that 5 second timer that quits the greeter might cause the greeter to quit, but the display server to still be running, correct?

I think so, but I'm not fully sure.

2024-06-26 17:21 UTC, n3rdopolis commented
OK, I can try to test that. If you want, I also have a diff, and backported SecureAttentionKey against logind v252 in Debian Stable, and I can make a .deb with it, that does not interfere with installed files (installs under /opt) from the main systemd package if you would also like to test, and don't want to deal with getting a system with v257

2024-07-01 03:00 UTC, n3rdopolis commented
@Vogtinator I am trying to replicate what you want me to replicate, I have x11-user enabled, I log in, and the greeter and the display server both quit

I try the Ctrl+Alt+Shift+Esc with the patched logind, and I can't seem to get a dormant display server with no greeter running, unless I am following the directions wrong

2024-07-01 10:14 UTC, Vogtinator commented
Maybe related to #1960 the greeter quits internally quickly enough that the 5s delay doesn't even trigger - but why does the code exist then? :confused:

2024-07-01 12:23 UTC, n3rdopolis commented
Is there anything you want me to try?

2024-07-01 12:29 UTC, Vogtinator commented
I'd like to know how exactly the greeter session (sddm-greeter + possibly display server) lifetime is handled first, to make sure that there's no weird case lingering around. Currently it's not that obvious.

2024-07-01 12:56 UTC, n3rdopolis commented
OK, I can try, but I am not sure if I am creative enough to figure out all the hypotheticals

I do see that it seems that at least in xorg-user, if I `pkill sddm-greeter` the display server also quits

2024-07-03 03:49 UTC, n3rdopolis commented
Any experiments you need me to try?

2024-07-08 21:40 UTC, n3rdopolis commented
I am sorry, I am not sure what needs to be done from here. I do know that killing the greeter seems to kill the xorg-user server

2024-07-09 07:11 UTC, Vogtinator commented
I'm not sure either. I only have hypothetical issues and don't see anything obviously wrong with the code, so let's just be optimistic and fix it later if necessary.

2024-07-09 07:11 UTC, Vogtinator approved these changes

2024-07-09 07:11 UTC, merged

2024-07-09 11:19 UTC, n3rdopolis commented
Thanks!